version: '3.4'
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    environment:
      - VITE_CLIENT_BASE_URL=http://192.168.200.2:8000
      - VITE_KEY_CLOAK_ADMIN_PANEL=http://192.168.200.2:8080
      - VITE_ANALYSES_BASE_URL=http://192.168.200.2:8001
      - VITE_IS_SSL=false

    command: sh -c "npm install && npm run build && npm run preview"
    ports:
      - '4173:4173'
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
