import { RoutePathType } from './types';

export const RoutesName = {
  HOME: 'home',
  SERVICES: 'services',
  PRODUCTS: 'products',
  OUR_SERVICES: 'our-services',
  RULES: 'rules',
  CODE_NAME: 'code-name',
  MY_PRODUCT: 'my-product',
  RULES_NAME: 'rules-name',
  SUPPORT: 'support',
  RULES_CODE: 'rules-code',
  MY_RULES: 'my-rules',
  DASHBOARD: 'dashboard',
  SETTINGS: 'settings',
  UNAUTHORIZED: 'unauthorized',
  RESET_PASSWORD: 'reset-password',
  MONITORING_SYSTEM: 'monitoring-systems',
  MONITORING_SYSTEM_GUIDE: 'monitoring-systems-guide',
  ADD_USER: 'add-user',
  USERS: 'users',
  SEND_PRODUCT: 'send-product',
};

export const ROUTES_PATH: Record<RoutePathType, string> = {
  home: '/',
  addUser: `/${RoutesName.USERS}/${RoutesName.ADD_USER}`,
  services: `/${RoutesName.SERVICES}`,
  servicesProducts: `/${RoutesName.SERVICES}/${RoutesName.PRODUCTS}`,
  servicesRules: `/${RoutesName.SERVICES}/${RoutesName.RULES}`,
  servicesMonitoringSystems: `/${RoutesName.SERVICES}/${RoutesName.MONITORING_SYSTEM_GUIDE}`,
  servicesRulesRetrieve: `/${RoutesName.SERVICES}/${RoutesName.RULES}/:id`,
  support: `/${RoutesName.SUPPORT}`,
  ourServices: `/${RoutesName.OUR_SERVICES}`,
  settings: `/${RoutesName.SETTINGS}`,
  unauthorized: `/${RoutesName.UNAUTHORIZED}`,
  login: `/`,
  dashboard: `/${RoutesName.DASHBOARD}`,
  myProduct: `/${RoutesName.MY_PRODUCT}`,
  myProductName: `/${RoutesName.MY_PRODUCT}/:productName`,
  myProductMyRules: `/${RoutesName.MY_PRODUCT}/${RoutesName.MY_RULES}`,
  myProductIpsList: `/${RoutesName.MY_PRODUCT}/ips-list`,
  myProductMyRulesRetrieve: `/${RoutesName.MY_PRODUCT}/${RoutesName.MY_RULES}/:id`,
  monitoringSystems: `/${RoutesName.MONITORING_SYSTEM}`,
  monitoringSystemsOne: `/${RoutesName.MONITORING_SYSTEM}/one`,
  monitoringSystemsTow: `/${RoutesName.MONITORING_SYSTEM}/tow`,
  users: `/${RoutesName.USERS}`,
  sendProduct: `/${RoutesName.SEND_PRODUCT}`,
};
